# Generated by Django 3.1.4 on 2020-12-14 11:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BottleClass',
            fields=[
                ('bottle_class', models.IntegerField(primary_key=True, serialize=False)),
                ('recycle_class', models.IntegerField()),
                ('point', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RUser',
            fields=[
                ('rfid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=10)),
                ('pw', models.CharField(max_length=20)),
                ('total_point', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=500)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('bottle_c', models.ForeignKey(db_column='bottle_class', on_delete=django.db.models.deletion.CASCADE, related_name='b_class', to='recycle.bottleclass')),
                ('rUser', models.ForeignKey(db_column='user_rfid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='r_user', to='recycle.ruser')),
            ],
        ),
    ]
