# Generated by Django 3.1.4 on 2020-12-15 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('region', models.CharField(max_length=100)),
                ('message_confirmation', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local1', models.CharField(max_length=100)),
                ('local2', models.CharField(max_length=100)),
                ('class1_full_rate', models.IntegerField(default=0)),
                ('class2_full_rate', models.IntegerField(default=0)),
                ('class3_full_rate', models.IntegerField(default=0)),
                ('partner', models.ForeignKey(db_column='partner_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='m_partner', to='recycle.partner')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_date', models.DateTimeField(auto_now_add=True)),
                ('class1_amount', models.IntegerField(default=0)),
                ('class2_amount', models.IntegerField(default=0)),
                ('class3_amount', models.IntegerField(default=0)),
                ('machine', models.ForeignKey(db_column='machine_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_id', to='recycle.machine')),
                ('partner', models.ForeignKey(db_column='machine', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner', to='recycle.partner')),
            ],
        ),
    ]
