# Generated by Django 3.1.4 on 2020-12-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0004_machine_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='tel',
            field=models.CharField(default='000-0000-0000', max_length=30),
        ),
    ]
