# Generated by Django 3.1.4 on 2020-12-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0005_partner_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='pw',
            field=models.CharField(default='0000', max_length=50),
        ),
    ]
