# Generated by Django 3.1.4 on 2020-12-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0006_bottle_machine_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='machine_id',
            field=models.IntegerField(default=0),
        ),
    ]
